### ISSUE TITLE
OS X에서 하스켈 쓰는 법 안내

### ISSUE THREAD

**Issue by simnalamburt** [haskell-kr/haskell-kr#1]
한국 하스켈 모임 안내문에서, 맥에서 하스켈 쓸때 [Haskell for Mac OS X](https://ghcformacosx.github.io/)가 권장되었던것 같은데, 막상 좀 써보니 저게 업데이트도 느리고 환경변수도 바꿔야하고 이런저런 불만이 있었습니다. 그냥 아래처럼 brew로 까는게 더 낫겠더라구요.

```
brew install ghc cabal-install haskell-stack
```

근데 지금보니 하스켈 까는법 안내문이 어디에 고정적으로 안내되어있던게 아니라, `data/meetup/*.md` 만들때마다 매번 복붙되어서 안내되어왔더라구요. Haskell for Mac OS X 대신 brew로 설치하는 PR을 날리고싶은데 어디에다가 날리면 좋을지 잘 모르겠습니다.

**Comment by xtendo-org** [comment]
적절하고 타당한 지적입니다. 감사합니다.

그건 그렇고 그냥 `brew install haskell-stack`만 해도 됩니다. (물론 이러면 시스템-레벨의 GHC는 없는데, 이게 초보자들에 대한 안내인 걸 생각하면 없는 게 더 낫다고 생각합니다. 샌드박스 아이솔레이션 없이 그냥 `ghci` 하는 게 불가능해진다는 게 오히려 장점이고요.)

그리고 이건 제가 잘 몰라서 그러는데... `brew`가 OS X 내장 명령어가 아니잖아요? 저도 OS X에서는 홈브루부터 당연히 설치하긴 하지만 이게 과연 모든 유저(특히 초보자)에게 "홈브루는 당연히 가지고 있겠지"라고 가정해도 되나요? 그게 상관 없다면 저야 `brew install haskell-stack`으로 안내하는 것에 대찬성입니다. 훨씬 더 간결하고 좋죠.

@dahlia ↑

만약 `brew install haskell-stack`으로 개정한다고 하면 몇 가지 방법이 있는데,
- 일단 [영어판 안내](https://github.com/haskell-kr/haskell-kr/blob/master/data/en.md)는 문서가 하나뿐이기 때문에 고치기도 쉽고 실제로 꼭 고쳐야 합니다.
- 한국어로 된 각 모임 공지들은 앞으로 공지할 때에만 변경하는 방법과 기존 공지까지 다 갈아버리는 <del>역사왜곡</del> 방법이 있는데 어느 쪽이든 @simnalamburt 님이 선호하는 방법으로 PR하셔도 무방합니다.

**Comment by dahlia** [comment]
음… 보통 대부분의 개발자용 매뉴얼에서는 “Homebrew를 먼저 설치해야 한다” 정도로 언급만 하고 지나갈 때가 많습니다. 물론 친절하게 링크 정도는 해주는 게 좋을 것 같네요.

**Comment by xtendo-org** [comment]
:+1:

그럼 "For OS X users ..." 부분을 "OS X users may simply [install Homebrew](http://brew.sh) and `brew install haskell-stack`." 정도로 수정하고, 한국어 쪽은... @simnalamburt 님이 과거 문서 <del>역사왜곡</del> 수정을 원하시면 수정하셔서 PR 주시면 반영할게요. 아무튼 다음 공지부터는 `brew install haskell-stack`으로 안내하겠습니다.

**Comment by simnalamburt** [comment]
아 글쿤여 좋은정보 감사합니다. 혼자서 좀 써보고 PR 날릴게요

**Comment by xtendo-org** [comment]
이제는 스택 설치 안내만 일괄적으로 제공하고 있습니다. 스택 설치 안내 페이지에 OS X / macOS 설치 안내도 잘 나와 있으니까 이제 문제 없을 거라고 생각하고 이슈를 닫을게요. 혹시 문제가 있으면 다시 열어주세요.
